### ISSUE TITLE
Encoding incompatibility when running cursor.py

### ISSUE THREAD

**Issue by hecmay** [rqlite/pyrqlite#21]
I am trying to use RQlite to replace Sqlite in my parallel computing project, and I encountered the encoding issue when running /pyrqlite/cursor.py:
> Traceback (most recent call last):
  File "mmm_tuner.py", line 58, in <module>
    GccFlagsTuner.main(argparser.parse_args())
  File "/home/sx233/test/opentuner/opentuner/measurement/interface.py", line 291, in main
    return TuningRunMain(cls(args, *pargs, **kwargs), args).main()
  File "/home/sx233/test/opentuner/opentuner/tuningrunmain.py", line 194, in main
    self.init()
  File "/home/sx233/test/opentuner/opentuner/tuningrunmain.py", line 176, in init
    self.search_driver = self.search_driver_cls(**driver_kwargs)
  File "/home/sx233/test/opentuner/opentuner/search/driver.py", line 74, in __init__
    self.session.flush()
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/pyrqlite/cursors.py", line 114, in execute
    operation = self._substitute_params(operation, parameters)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/pyrqlite/cursors.py", line 102, in _substitute_params
    return ''.join(subst)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xda in position 2: ordinal not in range(128)

Similar error will occur when I set the default python encoding format to be "utf-8" 
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xda in position 2: invalid continuation byte

and Sqlalchemy fails to insert and rollback:
> [     0s]    INFO sqlalchemy.engine.base.Engine: INSERT INTO tuning_run (uuid, program_version_id, machine_class_id, input_class_id, name, args, objective, state, start_date, end_date, final_config_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2017-09-11 10:14:32,577 INFO sqlalchemy.engine.base.Engine ('0d0a42787b78461a9b6ba19ba7199cf5', 1, None, None, 'unnamed', 'x\xdaMQ=o\xd4@\x10%!\xc7%\xbe|\x1fp\x04\x1aJ\x10\x12\t\x12U\xba\x90\xf2t\xae\x982Z\x8d\xd7s\xf6H\xeb\xf5\xce\xce\xba\xb8H\x91\xa0\xc3\xff\x97\x1f\xc0 ... (760 characters truncated) ... 91\xc5\xb2\x80"p\xc8B\x9e}#\xef\x96/`\xf1\xb0\x9d\x12F\xdb\x9a\xfb\xf7\x18\xe5[\x92\xb3\x11f\xcf\xf6\x96\xf7%L}o\xea!\xa8|\x18\x87\xea\xeb?\xf1,\xac(', '\x80\x02copentuner.search.objective\nMinimizeTime\nq\x01)\x81q\x02}q\x03U\x06driverq\x04Nsb.', 'QUEUED', '2017-09-11 10:14:32.559986', None, None)
[     0s]    INFO sqlalchemy.engine.base.Engine: ('0d0a42787b78461a9b6ba19ba7199cf5', 1, None, None, 'unnamed', 'x\xdaMQ=o\xd4@\x10%!\xc7%\xbe|\x1fp\x04\x1aJ\x10\x12\t\x12U\xba\x90\xf2t\xae\x982Z\x8d\xd7s\xf6H\xeb\xf5\xce\xce\xba\xb8H\x91\xa0\xc3\xff\x97\x1f\xc0 ... (760 characters truncated) ... 91\xc5\xb2\x80"p\xc8B\x9e}#\xef\x96/`\xf1\xb0\x9d\x12F\xdb\x9a\xfb\xf7\x18\xe5[\x92\xb3\x11f\xcf\xf6\x96\xf7%L}o\xea!\xa8|\x18\x87\xea\xeb?\xf1,\xac(', '\x80\x02copentuner.search.objective\nMinimizeTime\nq\x01)\x81q\x02}q\x03U\x06driverq\x04Nsb.', 'QUEUED', '2017-09-11 10:14:32.559986', None, None)
2017-09-11 10:14:32,578 INFO sqlalchemy.engine.base.Engine ROLLBACK
[     0s]    INFO sqlalchemy.engine.base.Engine: ROLLBACK

**Comment by zmedico** [comment]
Moved to https://github.com/rqlite/sqlalchemy-rqlite/issues/5.
